services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PG_DATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5550:5432"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:4.0.3-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    configs:
      - source: plugins
        target: /etc/rabbitmq/enabled_plugins
    ports:
      - "5672:5672"
      - "15672:15672"
      - "2883:1883"
configs:
  plugins:
    content: "[rabbitmq_management, rabbitmq_mqtt]."
networks:
  postgres:
    driver: bridge

volumes:
  postgres:
