server:
  port: 8082
spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5550/notification
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    template:
      exchange: internal.exchange
      default-receive-queue: notification.queue
      routing-key: internal.notification.routing-key
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0
    enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
